- name: Install Sync Repository
  hosts: localhost
  become: true
  vars:
    user_name: admin

  tasks:
  - name: Qubinode Installer Script for KVM configration
    ansible.builtin.git:
      repo: https://github.com/tosin2013/qubinode-installer.git
      dest: "/home/{{ user_name }}/qubinode-installer"
      version: master
    tags: qubinode-installer

  - name: Recursively change ownership of qubinode-installer directory 
    ansible.builtin.file:
      path: "/home/{{ user_name }}/qubinode-installer"
      state: directory
      recurse: yes
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: kcli-openshift4-baremetal repository for bare metal IPI
    ansible.builtin.git:
      repo: https://github.com/karmab/kcli-openshift4-baremetal.git
      dest: /root/kcli-openshift4-baremetal
      version: master
    tags: kcli-openshift4-baremetal

  - name: openshift-4-deployment-notes repository for manual assisted-installer
    ansible.builtin.git:
      repo: https://github.com/tosin2013/openshift-4-deployment-notes.git
      dest:  "/home/{{ user_name }}/openshift-4-deployment-notes"
      version: master
    tags: openshift-4-deployment-notes

  - name: Recursively change ownership of openshift-4-deployment-notes directory 
    ansible.builtin.file:
      path: /home/{{ user_name }}/openshift-4-deployment-notes
      state: directory
      recurse: yes
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: OpenShift All-in-One deployment automation repository
    ansible.builtin.git:
      repo: https://github.com/RHFieldProductManagement/openshift-aio.git
      dest:  /root/openshift-aio
      version: main
    tags: openshift-aio