#!/bin/bash 
# wait for journalctl to complete 
# journalctl -xf 

cat >/etc/resolv.conf<<EOF
# Generated by NetworkManager
search hsd1.ga.comcast.net lab.tosins-supermicro.io
nameserver 10.0.0.132
nameserver 10.0.0.239
EOF

dnf clean all
dnf install git unzip wget bind-utils python3-pip tar util-linux-user -y 

dnf install ncurses-devel curl -y
curl 'https://vim-bootstrap.com/generate.vim' --data 'editor=vim&langs=javascript&langs=go&langs=html&langs=ruby&langs=python' > ~/.vimrc

echo "configureing powerline"
git clone https://github.com/jotyGill/ezsh
cd ezsh
./install.sh -c 
bash /root/scripts/00_virtual.sh
bash /root/scripts/00_virtual.sh.redfish
REDFISH_ADDRESS=$(grep -m 1 redfish-virtualmedia /root/install-config.yaml | sed 's/        address: redfish-virtualmedia+//')
echo $REDFISH_ADDRESS || exit $?
curl $REDFISH_ADDRESS
redfish.py status
/root/scripts/01_patch_installconfig.sh
/root/scripts/02_packages.sh
/root/scripts/04_get_clients.sh
/root/scripts/05_cache.sh
/root/scripts/06_disconnected_quay.sh
/root/scripts/06_disconnected_mirror.sh
/root/scripts/06_disconnected_olm.sh
/root/scripts/09_deploy_openshift.sh
